import type { Ingredient } from "../types/ingredient";

export const INGREDIENTS = [
  {
    id: "gin",
    name: "Gin",
    category: "spirit",
    abv: 0.4,
    sweetness: 0.04,
    acidity: 0.03,
    bitterness: 0.28,
    body: 0.34,
    freshness: 0.62,
    color: { r: 232, g: 241, b: 236 },
    opacity: 0.18,
    fizz: 0,
    cloudiness: 0.02,
  },
  {
    id: "rum",
    name: "Rum",
    category: "spirit",
    abv: 0.4,
    sweetness: 0.28,
    acidity: 0.02,
    bitterness: 0.1,
    body: 0.52,
    freshness: 0.12,
    color: { r: 168, g: 91, b: 45 },
    opacity: 0.72,
    fizz: 0,
    cloudiness: 0.08,
  },
  {
    id: "vodka",
    name: "Vodka",
    category: "spirit",
    abv: 0.4,
    sweetness: 0.02,
    acidity: 0.02,
    bitterness: 0.06,
    body: 0.22,
    freshness: 0.28,
    color: { r: 238, g: 244, b: 244 },
    opacity: 0.12,
    fizz: 0,
    cloudiness: 0,
  },
  {
    id: "lemon",
    name: "Lemon",
    category: "citrus",
    abv: 0,
    sweetness: 0.12,
    acidity: 0.94,
    bitterness: 0.16,
    body: 0.24,
    freshness: 0.92,
    color: { r: 242, g: 206, b: 66 },
    opacity: 0.68,
    fizz: 0,
    cloudiness: 0.42,
  },
  {
    id: "lime",
    name: "Lime",
    category: "citrus",
    abv: 0,
    sweetness: 0.1,
    acidity: 0.9,
    bitterness: 0.24,
    body: 0.22,
    freshness: 0.96,
    color: { r: 151, g: 197, b: 66 },
    opacity: 0.7,
    fizz: 0,
    cloudiness: 0.4,
  },
  {
    id: "honey",
    name: "Honey",
    category: "sweetener",
    abv: 0,
    sweetness: 1,
    acidity: 0.04,
    bitterness: 0.02,
    body: 0.94,
    freshness: 0.05,
    color: { r: 210, g: 139, b: 40 },
    opacity: 0.88,
    fizz: 0,
    cloudiness: 0.3,
  },
  {
    id: "oolong",
    name: "Oolong Tea",
    category: "tea",
    abv: 0,
    sweetness: 0.04,
    acidity: 0.05,
    bitterness: 0.52,
    body: 0.48,
    freshness: 0.3,
    color: { r: 126, g: 78, b: 39 },
    opacity: 0.76,
    fizz: 0,
    cloudiness: 0.16,
  },
  {
    id: "soda",
    name: "Soda",
    category: "mixer",
    abv: 0,
    sweetness: 0,
    acidity: 0.08,
    bitterness: 0,
    body: 0.08,
    freshness: 0.82,
    color: { r: 236, g: 246, b: 246 },
    opacity: 0.08,
    fizz: 1,
    cloudiness: 0,
  },
] as const satisfies readonly Ingredient[];

export const INGREDIENTS_BY_ID = new Map(
  INGREDIENTS.map((ingredient) => [ingredient.id, ingredient]),
);
