import type { Ingredient } from "../types/ingredient";
import type { FlavorKey } from "../types/drink";

export const INGREDIENTS = [
  {
    id: "gin",
    name: "Gin",
    nameZh: "金酒",
    category: "spirit",
    abv: 0.4,
    sweetness: 0.04,
    acidity: 0.03,
    bitterness: 0.28,
    body: 0.34,
    freshness: 0.62,
    moodValence: 0.1,
    color: { r: 232, g: 241, b: 236 },
    opacity: 0.18,
    fizz: 0,
    cloudiness: 0.02,
    viscosity: 0.14,
    foam: 0.02,
  },
  {
    id: "rum",
    name: "Rum",
    nameZh: "朗姆酒",
    category: "spirit",
    abv: 0.4,
    sweetness: 0.28,
    acidity: 0.02,
    bitterness: 0.1,
    body: 0.52,
    freshness: 0.12,
    moodValence: 0.25,
    color: { r: 168, g: 91, b: 45 },
    opacity: 0.72,
    fizz: 0,
    cloudiness: 0.08,
    viscosity: 0.3,
    foam: 0.03,
  },
  {
    id: "vodka",
    name: "Vodka",
    nameZh: "伏特加",
    category: "spirit",
    abv: 0.4,
    sweetness: 0.02,
    acidity: 0.02,
    bitterness: 0.06,
    body: 0.22,
    freshness: 0.28,
    moodValence: 0,
    color: { r: 238, g: 244, b: 244 },
    opacity: 0.12,
    fizz: 0,
    cloudiness: 0,
    viscosity: 0.1,
    foam: 0.01,
  },
  {
    id: "lemon",
    name: "Lemon",
    nameZh: "柠檬汁",
    category: "citrus",
    abv: 0,
    sweetness: 0.12,
    acidity: 0.94,
    bitterness: 0.16,
    body: 0.24,
    freshness: 0.92,
    moodValence: 0.28,
    color: { r: 242, g: 206, b: 66 },
    opacity: 0.68,
    fizz: 0,
    cloudiness: 0.42,
    viscosity: 0.26,
    foam: 0.16,
  },
  {
    id: "lime",
    name: "Lime",
    nameZh: "青柠汁",
    category: "citrus",
    abv: 0,
    sweetness: 0.1,
    acidity: 0.9,
    bitterness: 0.24,
    body: 0.22,
    freshness: 0.96,
    moodValence: 0.35,
    color: { r: 151, g: 197, b: 66 },
    opacity: 0.7,
    fizz: 0,
    cloudiness: 0.4,
    viscosity: 0.28,
    foam: 0.16,
  },
  {
    id: "honey",
    name: "Honey",
    nameZh: "蜂蜜",
    category: "sweetener",
    abv: 0,
    sweetness: 1,
    acidity: 0.04,
    bitterness: 0.02,
    body: 0.94,
    freshness: 0.05,
    moodValence: 0.42,
    color: { r: 210, g: 139, b: 40 },
    opacity: 0.88,
    fizz: 0,
    cloudiness: 0.3,
    viscosity: 0.96,
    foam: 0.08,
  },
  {
    id: "oolong",
    name: "Oolong Tea",
    nameZh: "乌龙茶",
    category: "tea",
    abv: 0,
    sweetness: 0.04,
    acidity: 0.05,
    bitterness: 0.52,
    body: 0.48,
    freshness: 0.3,
    moodValence: -0.28,
    color: { r: 126, g: 78, b: 39 },
    opacity: 0.76,
    fizz: 0,
    cloudiness: 0.16,
    viscosity: 0.36,
    foam: 0.08,
  },
  {
    id: "soda",
    name: "Soda",
    nameZh: "苏打水",
    category: "mixer",
    abv: 0,
    sweetness: 0,
    acidity: 0.08,
    bitterness: 0,
    body: 0.08,
    freshness: 0.82,
    moodValence: 0.3,
    color: { r: 236, g: 246, b: 246 },
    opacity: 0.08,
    fizz: 1,
    cloudiness: 0,
    viscosity: 0.05,
    foam: 0.9,
  },
  {
    id: "campari",
    name: "Campari",
    nameZh: "金巴利",
    category: "aperitif",
    abv: 0.25,
    sweetness: 0.34,
    acidity: 0.12,
    bitterness: 0.86,
    body: 0.46,
    freshness: 0.26,
    moodValence: -0.42,
    color: { r: 196, g: 24, b: 30 },
    opacity: 0.88,
    fizz: 0,
    cloudiness: 0.04,
    viscosity: 0.26,
    foam: 0.02,
  },
  {
    id: "sweet-vermouth",
    name: "Sweet Vermouth",
    nameZh: "甜味美思",
    category: "fortified-wine",
    abv: 0.18,
    sweetness: 0.66,
    acidity: 0.12,
    bitterness: 0.36,
    body: 0.58,
    freshness: 0.18,
    moodValence: -0.1,
    color: { r: 127, g: 24, b: 32 },
    opacity: 0.86,
    fizz: 0,
    cloudiness: 0.08,
    viscosity: 0.38,
    foam: 0.03,
  },
  {
    id: "dry-vermouth",
    name: "Dry Vermouth",
    nameZh: "干味美思",
    category: "fortified-wine",
    abv: 0.18,
    sweetness: 0.12,
    acidity: 0.22,
    bitterness: 0.42,
    body: 0.38,
    freshness: 0.52,
    moodValence: -0.18,
    color: { r: 221, g: 211, b: 155 },
    opacity: 0.42,
    fizz: 0,
    cloudiness: 0.03,
    viscosity: 0.2,
    foam: 0.02,
  },
  {
    id: "simple-syrup",
    name: "Simple Syrup",
    nameZh: "糖浆",
    category: "sweetener",
    abv: 0,
    sweetness: 1,
    acidity: 0,
    bitterness: 0,
    body: 0.72,
    freshness: 0.02,
    moodValence: 0.38,
    color: { r: 240, g: 245, b: 244 },
    opacity: 0.18,
    fizz: 0,
    cloudiness: 0,
    viscosity: 0.82,
    foam: 0.02,
  },
  {
    id: "tonic",
    name: "Tonic Water",
    nameZh: "汤力水",
    category: "mixer",
    abv: 0,
    sweetness: 0.32,
    acidity: 0.24,
    bitterness: 0.58,
    body: 0.12,
    freshness: 0.86,
    moodValence: 0.12,
    color: { r: 236, g: 246, b: 246 },
    opacity: 0.08,
    fizz: 0.92,
    cloudiness: 0,
    viscosity: 0.06,
    foam: 0.68,
  },
  {
    id: "ginger-beer",
    name: "Ginger Beer",
    nameZh: "姜汁啤酒",
    category: "mixer",
    abv: 0,
    sweetness: 0.52,
    acidity: 0.18,
    bitterness: 0.22,
    body: 0.44,
    freshness: 0.72,
    moodValence: 0.48,
    color: { r: 214, g: 157, b: 53 },
    opacity: 0.58,
    fizz: 0.9,
    cloudiness: 0.22,
    viscosity: 0.22,
    foam: 0.78,
  },
  {
    id: "ad-milk",
    name: "AD Calcium Milk",
    nameZh: "AD 钙奶",
    category: "dairy",
    abv: 0,
    sweetness: 0.62,
    acidity: 0.2,
    bitterness: 0,
    body: 0.76,
    freshness: 0.26,
    moodValence: 0.35,
    color: { r: 245, g: 236, b: 214 },
    opacity: 1,
    fizz: 0,
    cloudiness: 0.98,
    viscosity: 0.62,
    foam: 0.36,
  },
  {
    id: "wangzai-milk",
    name: "Wangzai Milk",
    nameZh: "旺仔牛奶",
    category: "dairy",
    abv: 0,
    sweetness: 0.78,
    acidity: 0.08,
    bitterness: 0,
    body: 0.82,
    freshness: 0.18,
    moodValence: 0.58,
    color: { r: 247, g: 232, b: 204 },
    opacity: 1,
    fizz: 0,
    cloudiness: 1,
    viscosity: 0.68,
    foam: 0.34,
  },
  {
    id: "soy-milk",
    name: "Soy Milk",
    nameZh: "豆浆",
    category: "plant-milk",
    abv: 0,
    sweetness: 0.38,
    acidity: 0.05,
    bitterness: 0.04,
    body: 0.72,
    freshness: 0.28,
    moodValence: 0.18,
    color: { r: 235, g: 215, b: 172 },
    opacity: 1,
    fizz: 0,
    cloudiness: 1,
    viscosity: 0.58,
    foam: 0.42,
  },
  {
    id: "osmanthus-wine",
    name: "Osmanthus Wine",
    nameZh: "桂花酒",
    category: "floral-wine",
    abv: 0.12,
    sweetness: 0.7,
    acidity: 0.16,
    bitterness: 0.08,
    body: 0.58,
    freshness: 0.4,
    moodValence: 0.52,
    color: { r: 224, g: 158, b: 44 },
    opacity: 0.8,
    fizz: 0,
    cloudiness: 0.08,
    viscosity: 0.4,
    foam: 0.05,
  },
  {
    id: "umeshu",
    name: "Umeshu",
    nameZh: "青梅酒",
    category: "fruit-wine",
    abv: 0.12,
    sweetness: 0.74,
    acidity: 0.5,
    bitterness: 0.08,
    body: 0.56,
    freshness: 0.62,
    moodValence: 0.46,
    color: { r: 190, g: 181, b: 50 },
    opacity: 0.76,
    fizz: 0,
    cloudiness: 0.1,
    viscosity: 0.42,
    foam: 0.04,
  },
] as const satisfies readonly Ingredient[];

export const INGREDIENTS_BY_ID = new Map(
  INGREDIENTS.map((ingredient) => [ingredient.id, ingredient]),
);

const RACK_INGREDIENT_ORDER: Ingredient["id"][] = [
  "gin", "ad-milk", "rum", "campari", "vodka", "wangzai-milk", "lemon",
  "tonic", "dry-vermouth", "soy-milk", "honey", "ginger-beer", "oolong",
  "lime", "osmanthus-wine", "sweet-vermouth", "soda", "umeshu", "simple-syrup",
];

export const RACK_INGREDIENTS = RACK_INGREDIENT_ORDER.map(
  (ingredientId) => INGREDIENTS_BY_ID.get(ingredientId)!,
);

export function getDominantFlavorKey(ingredientId: Ingredient["id"] | null): FlavorKey | null {
  if (!ingredientId) return null;
  const ingredient = INGREDIENTS_BY_ID.get(ingredientId);
  if (!ingredient) return null;

  const values: Array<[FlavorKey, number]> = [
    ["sweetness", ingredient.sweetness],
    ["acidity", ingredient.acidity],
    ["bitterness", ingredient.bitterness],
    ["alcohol", ingredient.abv],
    ["freshness", ingredient.freshness],
    ["body", ingredient.body],
  ];
  return values.reduce((strongest, current) => current[1] > strongest[1] ? current : strongest)[0];
}
